### PR TITLE
Adds `rawMode` to disable serializing localStorage values

### PR DESCRIPTION
**Pull request by TylerFisher**
We've been integrating cross-storage with a localStorage ecosystem that does not serialize its values; thus, we needed a way to use cross-storage that did not depend on serialization. This PR adds a configuration option to the client init called `rawMode` that will make getting/setting values not rely on serialization.

Another way to do this would be to use native ES6 classes and create a `rawCrossStorageClient` subclass.

See #21 for more.

### CODE REVIEW

**Comment by JacksonGariety** [comment]
+1

**Comment by eads** [comment]
Bump! Just wanted to check on this. NPR Visuals has been using it in production for several months now.

**Comment by awhitehouse104** [comment]
+1 for this, fyi you left a console.log floating in there :)

**Comment by danielstjules** [comment]
Thanks for the PR! I've replied to https://github.com/zendesk/cross-storage/issues/21 I think what I'd rather see is the removal of serialization from `cross-storage` altogether

**Comment by danielstjules** [comment]
Thanks again! :)

**Pull request closed without merging**
